FORMAT: 1A
HOST: http://127.0.0.1:8080/v1/

# Beta Player API

Caution: all of these endpoints are still in development. These are not stable
intefaces.

Access live streams from the rain forest.

## Authentication [/player/login]
Token Based authentication is used throughout the API.

### Retrieve Token [POST]
From this endpoint we retrieve an anonymous token. These are tokens for which we
do not have any information (email, name, ...) about the user who requested it.
These tokens have limited access rights.

We need to add the guid (as x-auth-user) and token (as x-auth-token) as headers
to all further requests.

+ Request (application/json)

            { "password" : "1121" }


+ Response 200 (application/json; charset=utf-8)
Your password was correct and a token is included in the message.

    + Attributes(object)

        + token (object) - authentication token for other requests
            + guid (string) - user id (x-auth-user header)
            + token (string) - token value (x-auth-token header)
            + expires_at (string) - ISO 8601 date time string (in UTC)

    + Body

            {
                "token": {
                    "guid": "82905453-27f7-4c4f-a280-9743d0b4022c",
                    "token": "iwc3g2wd74eb4co5bt3dz49p1vq293rlrytirj6v",
                    "expires_at": "2016-05-17T12:02:04.530Z"
                }
            }

+ Request (application/json)

            { "password" : "1122" }

+ Response 401 (application/json; charset=utf-8)
Invalid password

    + Body

            {
              "message": "invalid password",
              "error": {
                "status": 401
              }
            }

+ Response 500 (application/json)
Internal server error

    + Body

            {
              "message": "error creating access token for audio player | database is not reachable",
              "error": {
                "status": 500
              }
            }
