FORMAT: 1A
HOST: http://127.0.0.1:8080/v1/

# Beta Player API

Caution: all of these endpoints are still in development. These are not stable
intefaces.

Access live streams from the rain forest.

## Authentication [/player/login]
Token Based authentication is used throughout the API.

### Retrieve Token [POST]
From this endpoint we retrieve an anonymous token. These are tokens for which we
do not have any information (email, name, ...) about the user who requested it.
These tokens have limited access rights.

We need to add the guid (as x-auth-user) and token (as x-auth-token) as headers
to all further requests.

+ Request (application/json)

            { "password" : "1121" }


+ Response 200 (application/json; charset=utf-8)
Your password was correct and a token is included in the message.

    + Attributes(object)

        + token (object) - authentication token for other requests
            + guid (string) - user id (x-auth-user header)
            + token (string) - token value (x-auth-token header)
            + expires_at (string) - ISO 8601 date time string (in UTC)

    + Body

            {
                "token": {
                    "guid": "82905453-27f7-4c4f-a280-9743d0b4022c",
                    "token": "iwc3g2wd74eb4co5bt3dz49p1vq293rlrytirj6v",
                    "expires_at": "2016-05-17T12:02:04.530Z"
                }
            }

+ Request (application/json)

            { "password" : "1122" }

+ Response 401 (application/json; charset=utf-8)
Invalid password

    + Body

            {
              "message": "invalid password",
              "error": {
                "status": 401
              }
            }

+ Response 500 (application/json)
Internal server error

    + Body

            {
              "message": "error creating access token for audio player | database is not reachable",
              "error": {
                "status": 500
              }
            }

## Meta Data [/player/web]
### Retrieve Streaming Information [GET]
Retrieves streaming information for curated and real-time streams about
(1) urls to download audio files, (2) stream-specific flick photo album and
(3) location information.

For token based authentication we need the guid and token information from Authentication/Login.
Note, you'll need to prepend a "token/" before the guid.

+ Request (application/json)

+ Response 200 (application/json; charset=utf-8)

    + Attributes (object)

        + streams (array[stream])


    + Body



            {
              "streams": [
                {
                  "guid": "6aa09bd6-c8a5-4da5-a808-8789f3d08e64",
                  "active": true,
                  "type": "playlist",
                  "shortname": "Amazon (Nightfall)",
                  "name": "Nightfall, Tembé Indigenous Territory",
                  "location": "Amazon, Parà, Brazil",
                  "timezone_offset": -3,
                  "description": "Nightfall, Tembé Indigenous Territory, Amazon Rainforest",
                  "flickr_photoset_id": "72157666271579426",
                  "urls": {
                    "audio": "/v1/guardians/0bdbb4a5d567/audio.json?starting_after=2016-03-22T01:15:00.000Z&order=ascending&limit=3"
                  }
                },
                {
                  "guid": "08f54f4b-999b-4bb7-a076-7ae3c97727cd",
                  "active": false,
                  "type": "stream",
                  "shortname": "Ecuador (LIVE)",
                  "name": "Live Stream, Tembé Indigenous Territory",
                  "location": "Amazon, Parà, Brazil",
                  "timezone_offset": -3,
                  "description": "Live Stream, Tembé Indigenous Territory",
                  "flickr_photoset_id": "72157666271579426",
                  "urls": {
                    "audio": "/v1/guardians/0bdbb4a5d567/audio.json"
                  }
                }
              ]
            }

# Data Structures

## stream (object)
+ active(boolean) - (new) whether the stream is currently active or not, this will be used for streams that will used for streams under construction
+ type (string) - 'playlist' (a curated stream from the past) or 'stream' (a live stream)
+ shortname (string) - for titles
+ name (string) - fully descriptive title
+ description (string) - a description of what we hear in the stream (especially for curated streams from the past), this could be used for the body of a player
+ location (string) - textual description of the location
+ timezone_offset (string) - UTC offset
+ flick_photoset_id (string) - this ID can be used to get photos from Flickr that are curated for this particular stream; this could be used for a slide show while streaming
+ urls
    + audio (string) - url to retrieve the audio data