version: "3.2"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - data-redis:/var/lib/redis
  timescaledb:
    image: "timescale/timescaledb:latest-pg12"
    ports:
      - "5432:5432"
    volumes:
      - data-timescaledb:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
  mysql:
    image: "mariadb:10.4"
    ports:
      - "3306:3306"
    volumes:
      - data-mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=rfcx_api
  sqs:
    image: roribio16/alpine-sqs
    ports:
      - "9324:9324"
      - "9325:9325"
volumes:
  data-timescaledb:
  data-mysql:
  data-redis:
