POST https://staging-api.rfcx.org/v2/guardians/6tjvs66wxudz/pings
x-auth-user: guardian/6tjvs66wxudz
x-auth-token: jku8ioy75ox6xf5iqtp3bl4j4czshhahkr4k5i38

{"json":"H4sIAAAAAAAAAF1RTU%2FDMAz9Lzlao7Kdb65IIE5DiDsK67pVqGOs7UCi%2B%2B%2FYBTFAimzHz35%2BcT5M15lLQ8FhzD4heSKwLoSUvQ1A1uVgGRF8jMgO0SxMfTSXH2avZqe9jrwnzI6dgL1kUkbigJQ4poCZMKRGoLbrW0Et4Qx%2BQ%2Ba0MEW5ukbA5aHsNuu7VspVl715vF0%2ByOXpILf766t3jUeJseJK50mrcZWrWGKRZG7GcqjbsjMn4d03SqySSqhtUyi6UDe4XmWd2g9K2sL58TZmkOdklgwCMVuXrM08rf8VsVjnQ3CQckSHNqmWTsSc67L3X5K69VC%2B%2B53PstA0lbFuX35yMiUm6V%2Ftxz9%2FEazIER2IBDyvfrXVjfeAgNMrUJKTPHucOimASDZP%2FfOM9sPsymyPaqV99%2FaHX74ULjLBtt8X8DLB6naH4XcRBnSqANgLCekPK8kGsMoVK794nFbiU0XTOHs2p083NcSnWQIAAA%3D%3D"}
