INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (1, 'ac', 'Acoustic Complexity Index', 1, 0, 5000);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (2, 'ad', 'Acoustic Diversity Index', 1, 0, 5);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (3, 'bi', 'Bioacoustic Index', 1, 0, 300);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (4, 'se', 'Spectral Entropy', 1, 0, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (5, 'te', 'Temporal Entropy', 1, 0, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (6, 'ae', 'Acoustic Evenness Index', 1, 0, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (7, 'snr', 'SNR', 1, 0, 100);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (8, 'aa', 'Acoustic Activity', 1, 0, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (9, 'aec', 'Acoustic Events Count', 1, 0, null);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (10, 'ead', 'Event Average Duration', 1, 0, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (11, 'fm25', 'Formant q25', 1, 0, 5000);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (12, 'fm50', 'Formant q50', 1, 0, 5000);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (13, 'fm75', 'Formant q75', 1, 0, 5000);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (14, 'fmi', 'Formant IQR', 1, 0, 5000);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (15, 'fml', 'Formant length', 1, 0, null);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (16, 'cm25', 'Chroma2 q25', 1, 0, null);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (17, 'cm50', 'Chroma2 q50', 1, 0, null);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (18, 'cm75', 'Chroma2 q75', 1, 0, null);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (19, 'cmm', 'Chroma2 MAD', 1, 0, null);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (20, 'cmi', 'Chroma2 IQR', 1, 0, null);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (21, 'lsf25', 'LSF q25', 1, 0, null);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (22, 'lsf50', 'LSF q50', 1, 0, null);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (23, 'lsf75', 'LSF q75', 1, 0, null);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (24, 'lsfm', 'LSF MAD', 1, 0, null);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (25, 'lsfi', 'LSF IQR', 1, 0, null);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (26, 'mfcc25', 'MFCC q25', 1, -1, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (27, 'mfcc50', 'MFCC q50', 1, -1, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (28, 'mfcc75', 'MFCC q75', 1, -1, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (29, 'mfccm', 'MFCC MAD', 1, 0, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (30, 'mfcci', 'MFCC IQR', 1, 0, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (31, 'obsir25', 'OBSIR q25', 1, -1, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (32, 'obsir50', 'OBSIR q50', 1, -1, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (33, 'obsir75', 'OBSIR q75', 1, -1, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (34, 'obsirm', 'OBSIR MAD', 1, 0, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (35, 'obsiri', 'OBSIR IQR', 1, 0, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (36, 'psh', 'Perceptual Sharpness', 1, 0, 10);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (37, 'psp', 'Perceptual Spread', 1, 0, 10);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (38, 'scf25', 'Spectral Crest Factor (Per Band) q25', 1, 0, 10);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (39, 'scf50', 'Spectral Crest Factor (Per Band) q50', 1, 0, 10);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (40, 'scf75', 'Spectral Crest Factor (Per Band) q75', 1, 0, 10);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (41, 'scfm', 'Spectral Crest Factor (Per Band) MAD', 1, 0, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (42, 'scfi', 'Spectral Crest Factor (Per Band) IQR', 1, 0, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (43, 'sd', 'Spectral Decrease', 1, 0, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (44, 'sf', 'Spectral Flatness', 1, 0, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (45, 'sx', 'Spectral Flux', 1, 0, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (46, 'sr', 'Spectral Rolloff', 1, 0, 10000);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (47, 'ss', 'Spectral Slope', 1, 0, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (48, 'sv', 'Spectral Variation', 1, 0, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (49, 'zcr', 'ZCR', 1, 0, 1);

INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (51, 'umap1', 'UMAP Dimension 1', 2, 0, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (52, 'umap2', 'UMAP Dimension 2', 2, 0, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (53, 'umap3', 'UMAP Dimension 3', 2, 0, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (54, 'umap4', 'UMAP Dimension 4', 2, 0, 1);
INSERT INTO indices (id, code, name, type_id, range_min, range_max) VALUES (55, 'umap5', 'UMAP Dimension 5', 2, 0, 1);
