name: 'EKS-CD-SEC'
on:
  workflow_dispatch:
  push:
    branches:
      - eks-branch
#      - staging
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  prepare:
    name: 'Prepare'
    uses: rfcx/cicd/.github/workflows/notify-prepare.yaml@master
    with:
      repo: rfcx-api
      workflow-id: cd.yaml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  configure:
    name: 'Configure'
    runs-on: ubuntu-latest
    outputs:
      namespace: ${{ steps.configuration.outputs.namespace }}
      environment: ${{ steps.configuration.outputs.environment }}
    steps:
      - name: 'Conditional environment'
        id: configuration
        run: |
          echo "::set-output name=namespace::eks-test-ns"
          if [[ "${{ needs.prepare.outputs.branch-name }}" == "master" ]]; then
            echo "::set-output name=environment::production"
          elif [[ "${{ needs.prepare.outputs.branch-name }}" == "eks-branch" ]]; then
            echo "::set-output name=environment::staging"
          else
            echo "::set-output name=environment::testing"
          fi

  deploy:
    name: 'Deploy core-api secrets'
    needs: [configure]
    uses: rfcx/cicd/.github/workflows/eks-reusable-k8s-deploy-sec.yaml@eks_cicd
    with:
      tag: ${{ needs.build.outputs.unique-tag }}
      app_name: core-api
      namespace: ${{ needs.configure.outputs.namespace }}
      environment: ${{ needs.configure.outputs.environment }}
      secrets_list: "AUTH0_CLIENT_ID,AUTH0_CLIENT_SECRET"
    secrets: inherit
#