name: 'EKS-CD-secrets'
on:
  workflow_dispatch:
  push:
    branches:
      - ga-secrets
#      - staging
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:

#  prepare:
#    name: 'Prepare'
#    uses: rfcx/cicd/.github/workflows/notify-prepare.yaml@master
#    with:
#      repo: rfcx-api
#      workflow-id: cd.yaml
#    secrets:
#      github-token: ${{ secrets.GITHUB_TOKEN }}

  configure:
    name: 'Configure'
    runs-on: ubuntu-latest
#    needs: [prepare]
    outputs:
      namespace: ${{ steps.configuration.outputs.namespace }}
    steps:
      - name: 'Conditional environment'
        id: configuration
        run: |
          echo "::set-output name=namespace::eks-test-ns"
#          if [[ "${{ needs.prepare.outputs.branch-name }}" == "master" ]]; then
#            echo "::set-output name=namespace::production"
#          elif [[ "${{ needs.prepare.outputs.branch-name }}" == "staging" ]]; then
#            echo "::set-output name=namespace::staging"
#          else
#            echo "::set-output name=namespace::testing"
#          fi
  get-secrets:
    name: 'Get secrets'
    runs-on: ubuntu-latest
    needs: [configure]
    environment: staging/noncore-api
    steps:
      - name: getsecrets
        run: |
          SECRETS_CONTEXT="${{ toJson(secrets) }}"
          echo "$SECRETS_CONTEXT" > "input.json"
          cat <<EOF >>test.py
          import json
          with open('input.json', 'r') as f:
              input_json = f.read()

          data = json.loads(input_json)

          for key, value in data.items():
              print(f'key: {key}, value: {value}')
          EOF
          python test.py
