name: 'EKS-CD-SEC'
on:
  workflow_dispatch:
  push:
    branches:
      - eks-branch
#      - staging
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:

  configure:
    name: 'Configure'
    runs-on: ubuntu-latest
    outputs:
      namespace: ${{ steps.configuration.outputs.namespace }}
      envmnt: ${{ steps.configuration.outputs.envmnt }}
    steps:
      - name: 'Conditional environment'
        id: configuration
        run: |
          echo "::set-output name=namespace::eks-test-ns"
          echo "::set-output name=envmnt::staging/core-api"

  deploy:
    name: 'Deploy'
    needs: [configure]
    uses: rfcx/cicd/.github/workflows/eks-reusable-k8s-deploy-sec.yaml@eks_cicd
    with:
      tag: ${{ needs.build.outputs.unique-tag }}
      namespace: ${{ needs.configure.outputs.namespace }}
      envmnt: ${{ needs.configure.outputs.envmnt }}
    secrets: inherit
#

