name: 'EKS-CD-SEC'
on:
  workflow_dispatch:
  push:
    branches:
      - eks-branch
#      - staging
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  configure:
    name: 'Configure'
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
    outputs:
      namespace: ${{ steps.configuration.outputs.namespace }}
      environment: ${{ steps.configuration.outputs.environment }}
    steps:
      - name: 'Conditional environment'
        id: configuration
        run: |
          echo "::set-output name=namespace::eks-test-ns"
          if [[ "$BRANCH_NAME" == "master" ]]; then
            echo "::set-output name=environment::production"
          elif [[ "$BRANCH_NAME" == "eks-branch" ]]; then
            echo "::set-output name=environment::staging"
          else
            echo "::set-output name=environment::testing"
          fi

  deploy:
    name: 'Deploy core-api secrets'
    needs: [configure]
    uses: rfcx/cicd/.github/workflows/eks-reusable-k8s-deploy-sec.yaml@eks_cicd
    with:
      tag: ${{ needs.build.outputs.unique-tag }}
      namespace: ${{ needs.configure.outputs.namespace }}
      environment: ${{ needs.configure.outputs.environment }}/core-api
      secrets_list: "AUTH0_CLIENT_ID,AUTH0_CLIENT_SECRET,AWS_ACCESS_KEY_ID,AWS_SECRET_KEY,NEW_RELIC_LICENSE_KEY,POSTGRES_PASSWORD,POSTGRES_USER,STREAM_TOKEN_SALT"
    secrets: inherit

