name: 'EKS-CD'
on:
  workflow_dispatch:
  push:
    # TODO: change branches to staging and master once development is finished
    branches:
      - eks-branch

concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:

  configure:
    name: 'Configure'
    if: ${{ vars.EKS_CD_ENABLED == 'true' }}
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
    outputs:
      cluster: ${{ steps.configuration.outputs.cluster }}
      namespace: ${{ steps.configuration.outputs.namespace }}
      # aws_access_key_id: ${{ steps.configuration.outputs.aws_access_key_id }}
      # aws_secret_access_key: ${{ steps.configuration.outputs.aws_access_key_id }}
    steps:
      - name: 'Conditional environment'
        # env:
        #   AWS_ACCESS_KEY_ID_PROD_APP_DEPLOY: ${{ secrets.AWS_ACCESS_KEY_ID_PROD_APP_DEPLOY }}
        #   AWS_SECRET_ACCESS_KEY_PROD_APP_DEPLOY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD_APP_DEPLOY }}
        #   AWS_ACCESS_KEY_ID_NONPROD_APP_DEPLOY: ${{ secrets.AWS_ACCESS_KEY_ID_NONPROD_APP_DEPLOY }}
        #   AWS_SECRET_ACCESS_KEY_NONPROD_APP_DEPLOY: ${{ secrets.AWS_SECRET_ACCESS_KEY_NONPROD_APP_DEPLOY }}
        id: configuration
        run: |
          if [[ "$BRANCH_NAME" == "master" ]]; then
            echo "cluster=prod" >> $GITHUB_OUTPUT
            echo "namespace=production" >> $GITHUB_OUTPUT
          elif [[ "$BRANCH_NAME" == "staging" ]]; then
            echo "namespace=staging" >> $GITHUB_OUTPUT
          else
            echo "namespace=testing" >> $GITHUB_OUTPUT
          fi
          if [[ "$BRANCH_NAME" != "master" ]]; then
            echo "cluster=nonprod" >> $GITHUB_OUTPUT
          fi

  build:
    name: 'Build'
    if: ${{ vars.EKS_CD_ENABLED == 'true' }}
    needs: [configure]
#    uses: rfcx/cicd/.github/workflows/ecr-build-push.yaml@master
    uses: rfcx/rfcx-api/.github/workflows/eks-ecr-build-push.yaml@eks-branch
    with:
      dockerfile: build/Dockerfile
      targets: "[\"core-api\",\"core-tasks\",\"noncore-api\",\"noncore-mqtt\"]"
      tag-environment: ${{ needs.configure.outputs.namespace }}
      tag-latest: ${{ needs.configure.outputs.namespace == 'production' }}
      # cluster: ${{ needs.configure.outputs.cluster }}
    secrets:
      aws-access-key-id: ${{ ([[ needs.configure.outputs.cluster == 'prod' ]] && secrets.AWS_ACCESS_KEY_ID_PROD_APP_DEPLOY || secrets.AWS_ACCESS_KEY_ID_NONPROD_APP_DEPLOY) }}
      aws-secret-access-key: ${{ ([[ needs.configure.outputs.cluster == 'prod' ]] && secrets.AWS_SECRET_ACCESS_KEY_PROD_APP_DEPLOY || secrets.AWS_SECRET_ACCESS_KEY_NONPROD_APP_DEPLOY }}
      # aws-access-key-id: ${{ needs.configure.outputs.namespace == 'prod' ? secrets.AWS_ACCESS_KEY_ID_PROD_APP_DEPLOY : secrets.AWS_ACCESS_KEY_ID_NONPROD_APP_DEPLOY }}
    #   aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_NONPROD_APP_DEPLOY }}

  deploy-core-api-secrets:
    name: 'Deploy core-api secrets'
    if: ${{ vars.EKS_CD_ENABLED == 'true' }}
    needs: [configure, build]
    uses: rfcx/cicd/.github/workflows/eks-reusable-k8s-deploy-sec.yaml@eks_cicd
    with:
      namespace: ${{ needs.configure.outputs.namespace }}
      environment: ${{ needs.configure.outputs.environment }}/core-api
      secrets_name: core-secrets
      secrets_list: "AUTH0_CLIENT_ID,AUTH0_CLIENT_SECRET,AWS_ACCESS_KEY_ID,AWS_SECRET_KEY,NEW_RELIC_LICENSE_KEY,POSTGRES_PASSWORD,POSTGRES_USER,STREAM_TOKEN_SALT"
    secrets: inherit

  deploy-noncore-api-secrets:
    name: 'Deploy noncore-api secrets'
    if: ${{ vars.EKS_CD_ENABLED == 'true' }}
    needs: [configure, build]
    uses: rfcx/cicd/.github/workflows/eks-reusable-k8s-deploy-sec.yaml@eks_cicd
    with:
      namespace: ${{ needs.configure.outputs.namespace }}
      environment: ${{ needs.configure.outputs.environment }}/noncore-api
      secrets_name: noncore-secrets
      secrets_list: "AUTH0_CLIENT_ID,AUTH0_CLIENT_SECRET,AWS_ACCESS_KEY_ID,AWS_SECRET_KEY,CLASSY_CLIENT_ID,CLASSY_CLIENT_SECRET,FIREBASE_CLIENT_EMAIL_PLAYER_APP,FIREBASE_CLIENT_EMAIL_RANGER_APP,FIREBASE_PRIVATE_KEY_PLAYER_APP,FIREBASE_PRIVATE_KEY_RANGER_APP,GUARDIAN_KEYSTORE_PASSPHRASE,MAILCHIMP_KEY,MANDRILL_KEY,MQTT_BROKER_PASSWORD,MQTT_BROKER_USER,NEW_RELIC_LICENSE_KEY,POSTGRES_PASSWORD,POSTGRES_USER,RECAPTCHA_V3_SECRET_KEY,STRIPE_SECRET_KEY,TWILIO_ACCOUNT_SID,TWILIO_AUTH_TOKEN"
    secrets: inherit

  deploy:
    name: 'Deploy'
    if: ${{ vars.EKS_CD_ENABLED == 'true' }}
    needs: [configure, build]
    uses: rfcx/rfcx-api/.github/workflows/eks-reusable-k8s-deploy.yaml@eks-branch
    with:
      tag: ${{ needs.build.outputs.unique-tag }}
      namespace: ${{ needs.configure.outputs.namespace }}
    secrets:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_NONPROD_APP_DEPLOY }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_NONPROD_APP_DEPLOY }}

#  notify:
#    name: 'Notify'
#    if: ${{ always() }}
#    needs: [prepare, build, deploy]
#    uses: rfcx/cicd/.github/workflows/notify-send.yaml@master
#    with:
#      repo: rfcx-api
#      branch-name: ${{ needs.prepare.outputs.branch-name }}
#      workflow-id: cd.yaml
#      previous-run-id: ${{ needs.prepare.outputs.previous-run-id }}
#      status: ${{ needs.deploy.result }}
#      always: true
#      notification-title: 'CD: APIs'
#      notification-footer: "Build: ${{ needs.build.result || 'n/a' }} | Deploy: ${{ needs.deploy.result || 'n/a' }}"
#      notification-success-statement: '{0} deployed the build!'
#    secrets:
#      slack-webhook: ${{ secrets.SLACK_ALERT_COREDT_WEBHOOK }}
#      github-token: ${{ secrets.GITHUB_TOKEN }}
