on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
        required: false
      branch-name:
        description: Branch name
        type: string
        required: false
      lint:
        description: Run linting
        type: boolean
        default: true
        required: false
      test:
        description: Run tests
        type: boolean
        default: true
        required: false
    outputs:
      build-outcome:
        description: Build outcome
        value: ${{ jobs.build.outputs.build-outcome }}
      lint-outcome:
        description: Lint outcome
        value: ${{ jobs.build.outputs.lint-outcome }}
      test-outcome:
        description: Test outcome
        value: ${{ jobs.build.outputs.test-outcome }}
jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    outputs:
      lint-outcome: ${{ steps.lint.outcome }}
      test-outcome: ${{ steps.test.outcome }}

    services:
      postgres:
        image: timescale/timescaledb:latest-pg14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 'Setup: Node'
        # v3 (3.1.0) @ 01 Apr 2022 https://github.com/actions/setup-node/tags
        uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236
        with:
          node-version: '16'

      - name: 'Setup: Git checkout'
        uses: actions/checkout@3.4.0

      - name: 'Setup: Database init scripts'
        run: |
          find test/init.d -type f | sort | PGPASSWORD=test xargs -n1 -I % psql -U postgres -h 127.0.0.1 -p 5433 -f %

      - name: 'Setup: Load npm dependencies cache'
        # v3 (3.0.1) @ 30 Mar 2022 https://github.com/actions/cache/tags
        uses: actions/cache@136d96b4aee02b1f0de3ba493b1d47135042d9c0
        id: setup-npm-cache
        with:
          path: '**/node_modules'
          key: npm-${{ runner.os }}-${{ inputs.branch-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-${{ inputs.branch-name }}-
            npm-${{ runner.os }}-

      - name: 'Setup: Install dependencies'
        if: steps.setup-npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: 'Setup: Load ESLint cache'
        if: ${{ inputs.lint }}
        # v3 (3.0.1) @ 30 Mar 2022 https://github.com/actions/cache/tags
        uses: actions/cache@136d96b4aee02b1f0de3ba493b1d47135042d9c0
        with:
          path: |
            .eslintcache
            */*/.eslintcache
          key: eslint-${{ runner.os }}-${{ inputs.branch-name }}
          restore-keys: |
            eslint-${{ runner.os }}-

      - name: 'Verify: Lint'
        if: ${{ inputs.lint }}
        id: lint
        run: npm run lint

      - name: 'Verify: Integration + Unit Tests'
        if: ${{ inputs.test }}
        id: test
        run: npm run jest
        env:
          NODE_ENV: test
