on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
        required: false
      tag: 
        description: Image tag to deploy
        type: string
        required: true
      namespace:
        description: Kubernetes namespace
        type: string
        required: true
    secrets:
      kube-config:
        description: KUBE_CONFIG file
        required: true
jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: 'Setup: Git checkout'
        # v3 (3.0.0) @ 02 Mar 2022 https://github.com/actions/checkout/tags
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: 'Deploy: Set image version'
        run: |
          find build -name "*.yaml" -exec sed -i s/:latest/:${{ inputs.tag }}/g {} +

      - name: 'Deploy: Kubernetes apply'
        # v1 (1.21.2) @ 03 Nov 2021 https://github.com/actions-hub/kubectl/tags
        uses: actions-hub/kubectl@365773786ebd92c7b36b6ab80e17d4a213ab0cd1
        env:
          KUBE_CONFIG: ${{ secrets.kube-config1 }}
        with:
          args: apply -R -f build/${{ inputs.namespace }}

      - name: 'Deploy: Kubernetes verify core-api'
        # v1 (1.21.2) @ 03 Nov 2021 https://github.com/actions-hub/kubectl/tags
        uses: actions-hub/kubectl@365773786ebd92c7b36b6ab80e17d4a213ab0cd1
        env:
          KUBE_CONFIG: ${{ secrets.kube-config1 }}
        with:
          args: rollout status deployment/core-api --namespace=${{ inputs.namespace }}
      
      - name: 'Deploy: Kubernetes verify core-tasks'
        # v1 (1.21.2) @ 03 Nov 2021 https://github.com/actions-hub/kubectl/tags
        uses: actions-hub/kubectl@365773786ebd92c7b36b6ab80e17d4a213ab0cd1
        env:
          KUBE_CONFIG: ${{ secrets.kube-config1 }}
        with:
          args: rollout status deployment/core-tasks --namespace=${{ inputs.namespace }}
        
      - name: 'Deploy: Kubernetes verify media-api'
        if: ${{ inputs.namespace == 'production' }}
        # v1 (1.21.2) @ 03 Nov 2021 https://github.com/actions-hub/kubectl/tags
        uses: actions-hub/kubectl@365773786ebd92c7b36b6ab80e17d4a213ab0cd1
        env:
          KUBE_CONFIG: ${{ secrets.kube-config1 }}
        with:
          args: rollout status deployment/media-api --namespace=${{ inputs.namespace }}

      - name: 'Deploy: Kubernetes verify noncore-api'
        # v1 (1.21.2) @ 03 Nov 2021 https://github.com/actions-hub/kubectl/tags
        uses: actions-hub/kubectl@365773786ebd92c7b36b6ab80e17d4a213ab0cd1
        env:
          KUBE_CONFIG: ${{ secrets.kube-config1 }}
        with:
          args: rollout status deployment/noncore-api --namespace=${{ inputs.namespace }}

      - name: 'Deploy: Kubernetes verify noncore-mqtt'
        # v1 (1.21.2) @ 03 Nov 2021 https://github.com/actions-hub/kubectl/tags
        uses: actions-hub/kubectl@365773786ebd92c7b36b6ab80e17d4a213ab0cd1
        env:
          KUBE_CONFIG: ${{ secrets.kube-config1 }}
        with:
          args: rollout status deployment/noncore-mqtt --namespace=${{ inputs.namespace }}
