on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
        required: false
      branch-name:
        description: Branch name
        type: string
        required: false
      lint:
        description: Run linting
        type: boolean
        default: true
        required: false
      test:
        description: Run tests
        type: boolean
        default: true
        required: false
    outputs:
      build-outcome:
        description: Build outcome
        value: ${{ jobs.build.outputs.build-outcome }}
      lint-outcome:
        description: Lint outcome
        value: ${{ jobs.build.outputs.lint-outcome }}
      test-outcome:
        description: Test outcome
        value: ${{ jobs.build.outputs.test-outcome }}
jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    outputs:
      lint-outcome: ${{ steps.lint.outcome }}
      test-outcome: ${{ steps.test.outcome }}

    steps:
      - name: 'Setup: Node'
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        # v2 (2.4.1) @ 03 Nov 2021 https://github.com/actions/setup-node/tags
        with:
          node-version: '16'

      - name: 'Setup: Git checkout'
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        # v2 (2.4.0) @ 03 Nov 2021 https://github.com/actions/checkout/tags

      - name: 'Setup: Load npm dependencies cache'
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353
        # v2 (2.1.6) @ 03 Nov 2021 https://github.com/actions/cache/tags
        id: setup-npm-cache
        with:
          path: '**/node_modules'
          key: npm-${{ runner.os }}-${{ inputs.branch-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-${{ inputs.branch-name }}-
            npm-${{ runner.os }}-

      - name: 'Setup: Install dependencies'
        if: steps.setup-npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: 'Setup: Load ESLint cache'
        if: ${{ inputs.lint }}
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353
        # v2 (2.1.6) @ 03 Nov 2021 https://github.com/actions/cache/tags
        with:
          path: |
            .eslintcache
            */*/.eslintcache
          key: eslint-${{ runner.os }}-${{ inputs.branch-name }}
          restore-keys: |
            eslint-${{ runner.os }}-

      - name: 'Verify: Lint'
        if: ${{ inputs.lint }}
        id: lint
        run: npm run lint

      - name: 'Verify: Unit Test'
        if: ${{ inputs.test }}
        id: test
        run: npm run jest
